DROP TABLE IF EXISTS LIBRARY_TABLE;

CREATE TABLE LIBRARY_TABLE(
LIBRARY_ID INT NOT NULL AUTO_INCREMENT,
LIBRARY_NAME VARCHAR(500) NOT NULL,
LIBRARY_LOCATION VARCHAR(500) NOT NULL,
TELEPHONE VARCHAR(100) NOT NULL,
CONSTRAINT LIBRARY_TABLE_PK PRIMARY KEY (LIBRARY_ID)
);
DROP TABLE IF EXISTS BOOKS_TABLE;

CREATE TABLE BOOKS_TABLE(
BOOK_ID INT NOT NULL AUTO_INCREMENT,
LIBRARY_ID INT NOT NULL ,
BOOK_NAME VARCHAR(500) NOT NULL,
AUTHOR_NAME VARCHAR(500) NOT NULL,
BOOK_TYPE VARCHAR(500) NOT NULL,
AVAILABILITY VARCHAR(10) NOT NULL,
PUBLISHER_NAME VARCHAR(500) NOT NULL,
CONSTRAINT BOOKS_TABLE_PK PRIMARY KEY (BOOK_ID),
CONSTRAINT BOOKS_TABLE_FK1 FOREIGN KEY (LIBRARY_ID) REFERENCES LIBRARY_TABLE(LIBRARY_ID)
);